name: Deploy Frontend + Backend to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  BACKEND_REPO: devops-app-backend
  FRONTEND_REPO: devops-app-frontend
  ECS_CLUSTER: devops-app-cluster
  BACKEND_SERVICE: devops-app-service
  FRONTEND_SERVICE: devops-app-frontend-service

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
# =========================
# Checkout
# =========================
      - uses: actions/checkout@v4

# =========================
# AWS Login
# =========================
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

# =========================
# ECR Login
# =========================
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

# =========================
# BACKEND BUILD & PUSH
# =========================
      - name: Build backend
        run: |
          docker build -t backend -f app/backend/Dockerfile app/

      - name: Tag backend
        run: |
          docker tag backend:latest \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG

          docker tag backend:latest \
          ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:latest

      - name: Push backend
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$BACKEND_REPO:latest

# =========================
# FRONTEND BUILD & PUSH
# =========================
      - name: Build frontend
        run: |
         docker build -t frontend -f app/frontend/Dockerfile app/

      - name: Tag frontend
        run: |
          docker tag frontend:latest \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG

          docker tag frontend:latest \
          ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:latest

      - name: Push frontend
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$FRONTEND_REPO:latest

# =========================
# DEPLOY BACKEND
# =========================
      - name: Deploy backend
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $BACKEND_SERVICE \
            --force-new-deployment

# =========================
# DEPLOY FRONTEND
# =========================
      - name: Deploy frontend
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $FRONTEND_SERVICE \
            --force-new-deployment